server:
  port: 1111

spring:
  application:
     name: Apigateway
  cloud:
    gateway:
      routes:
      - id: 
        uri: http://localhost:8000/
        predicates:
        - Path=/admin/**
      - id: 
        uri: http://localhost:8080/
        predicates:
        - Path=/userDetails/**
      - id: 
        uri: http://localhost:8081/
        predicates:
        - Path=/product/**
      - id: 
        uri: http://localhost:8082/
        predicates:
        - Path=/order/**
      - id: 
        uri: http://localhost:8083/
        predicates:
        - Path=/doPay/**
      - id: 
        uri: http://localhost:8084/
        predicates:
        - Path=/cartDetails/**
     
